### ISSUE TITLE
DispatchIndirect help patch needed

### ISSUE THREAD

**Issue by letmp** [mrvux/dx11-vvvv-girlpower#24]
Can someone provide a help patch (for example as addition to https://github.com/mrvux/dx11-vvvv-girlpower/tree/master/girlpower/sm5/directcompute/indirectlookup ) that shows how to use the DispatchIndirect node to access filtered bufferdata in a computeshader?

**Comment by mrvux** [comment]
Actually forgot that one, but there is one now:
https://github.com/mrvux/dx11-vvvv-girlpower/tree/master/girlpower/sm5/directcompute/dispatchindirect
